services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZAlgoliaSearchEngine\Command\:
        resource: '../../Command'

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\:
        resource: '../../Core'

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Indexer:
        arguments:
            $logger: '@logger'
            $persistenceHandler: '@ezpublish.api.storage_engine'
            $connection: '@ezpublish.persistence.connection'
            $searchHandler: '@Novactive\Bundle\eZAlgoliaSearchEngine\Core\Handler'
        lazy: true
        tags:
            - { name: ezplatform.search_engine.indexer, alias: algolia }

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Handler:
        bind:
            $contentSearch: '@ezplatform.search.algolia.query.content.search'
            $locationSearch: '@ezplatform.search.algolia.query.location.search'
        arguments:
            $gateway: '@ezpublish.search.legacy.gateway.content'
            $locationGateway: '@ezpublish.search.legacy.gateway.location'
            $indexerGateway: '@eZ\Publish\Core\Search\Legacy\Content\WordIndexer\Gateway\DoctrineDatabase'
            $contentMapper: '@ezpublish.persistence.legacy.content.mapper'
            $locationMapper: '@ezpublish.persistence.legacy.location.mapper'
            $languageHandler: '@ezpublish.spi.persistence.language_handler'
            $mapper: '@ezpublish.search.legacy.fulltext_mapper'
        lazy: true
        tags:
            - { name: ezplatform.search_engine, alias: algolia }

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Converter:
        arguments:
            $persistenceHandler: '@ezpublish.api.storage_engine'
            $fieldRegistry: '@ezpublish.search.common.field_registry'
            $fieldNameGenerator: '@ezpublish.search.common.field_name_generator'
            $fieldTypeRegistry: '@ezpublish.persistence.field_type_registry'

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\DocumentSerializer:
        arguments:
            $fieldValueMapper: '@ezpublish.search.common.field_value_mapper.aggregate'
            $fieldNameGenerator: '@ezpublish.search.common.field_name_generator'

    # Search

    ezplatform.search.algolia.query.content.search:
        class: Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\Search
        arguments:
            $resultExtractor: '@Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\ContentResultsExtractor'
            $dispatcherVisitor: '@ezplatform.search.algolia.query.content.facet_builder_visitor.dispatcher'

    ezplatform.search.algolia.query.location.search:
        class: Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\Search
        arguments:
            $resultExtractor: '@Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\LocationResultsExtractor'
            $dispatcherVisitor: '@ezplatform.search.algolia.query.location.facet_builder_visitor.dispatcher'

    # Visitors

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\FacetBuilderVisitor\ContentTypeVisitor:
        tags:
            - { name: ezplatform.search.algolia.query.content.facet_builder_visitor }
            - { name: ezplatform.search.algolia.query.location.facet_builder_visitor }

    ezplatform.search.algolia.query.content.facet_builder_visitor.dispatcher:
        class: Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\FacetBuilderVisitor\DispatcherVisitor
        arguments:
            $visitors: !tagged ezplatform.search.algolia.query.content.facet_builder_visitor

    ezplatform.search.algolia.query.location.facet_builder_visitor.dispatcher:
        class: Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\FacetBuilderVisitor\DispatcherVisitor
        arguments:
            $visitors: !tagged ezplatform.search.algolia.query.location.facet_builder_visitor

    # Extractors

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\ContentResultsExtractor:
        arguments:
            $contentHandler: '@ezpublish.spi.persistence.content_handler'

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\LocationResultsExtractor:
        arguments:
            $locationHandler: '@ezpublish.spi.persistence.location_handler'

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\FacetResultExtractor\FacetResultExtractor:
        alias: Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\FacetResultExtractor\DispatcherResultExtractor

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\FacetResultExtractor\DispatcherResultExtractor:
        arguments:
            $extractors: !tagged_iterator ezplatform.search.algolia.query.facet_result_extractor

    Novactive\Bundle\eZAlgoliaSearchEngine\Core\Query\ResultExtractor\FacetResultExtractor\ContentTypeResultExtractor:
        tags:
            - { name: ezplatform.search.algolia.query.facet_result_extractor }